######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 10 02:34:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += a.cpp
