######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 19 17:59:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloqt.cpp
