/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef your_thrift_file_CONSTANTS_H
#define your_thrift_file_CONSTANTS_H

#include "your_thrift_file_types.h"

namespace Test {

class your_thrift_fileConstants {
 public:
  your_thrift_fileConstants();

};

extern const your_thrift_fileConstants g_your_thrift_file_constants;

} // namespace

#endif
