#!/usr/bin/perl

#########################################################################################################################
# target is to know C, C++, Java, Python, Perl, Ruby, Go, Lua, PHP, Objective C, JavaScript(since its quite famous),    #
# Lisp (for satisfaction), Prolog, Dart, Ada,                                                                           #
# Erlang and Haskell too if time permits,                                                                               #
# Logo as they say its lisp w/o parantheses, R, Tcl/tk and ML too if you are bored                                      #
#########################################################################################################################


#########################################################################################################################
# Current status:                                                                                                       #
#                                                                                                                       #
# Knows Well:            C, C++, Python, PHP, Javascript,                                                               #
# In progress:           Java, Perl, Ruby, Go, Lua, Lisp,                                                               #
# Tried somedays back:   Prolog, Dart,                                                                                  #
# Start soon:            Objective C, Ada, Erlang, Haskell, Logo, Tcl/tk, R, ML,                                        #
#                                                                                                                       #
#                                                                                                                       #
#                                                                                                                       #
#########################################################################################################################
#                                                                                                                       #
#                                                                                                                       #
#                                                                                                                       #
# How to go furthur:                                                                                                    #
# Start with  Ada, Erlang and Haskell together. They seem to go together                                                #
#             as trio of Python, Perl, Ruby, Logo                                                                       #
# About Tcl/tk- Similar to python only start someday soon                                                               #
# About R, ML. See what you can about them. Don't try too hard                                                  #
# About Objective C: Lets C what goes around and comes around.                                                          #
#########################################################################################################################
